# Generated by Django 4.2 on 2025-07-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_orderresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершённый'), ('cancelled', 'Отменённый')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='orderresponse',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderRespondLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
