# Generated by Django 4.2 on 2025-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status_orderresponse_message_orderrespondlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
