# Generated by Django 4.2 on 2025-07-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_blocked',
        ),
    ]
