# Generated by Django 4.2 on 2025-07-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_blocked'),
        ('orders', '0005_remove_order_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profession'),
        ),
        migrations.AddField(
            model_name='order',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersubregion'),
        ),
    ]
