# Generated by Django 4.2 on 2025-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_category_profession_order_subregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='categories'),
            preserve_default=False,
        ),
    ]
