# Generated by Django 5.2.3 on 2025-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Заказчик', 'Заказчик'), ('Испольнитель', 'Испольнитель')], max_length=15, null=True, verbose_name='Роли'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
