# Generated by Django 5.2.3 on 2025-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Заказчик', 'Заказчик'), ('Исполнитель', 'Исполнитель')], max_length=15, null=True, verbose_name='Роли'),
        ),
    ]
