# Generated by Django 5.2.3 on 2025-07-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
    ]
