# Generated by Django 4.2 on 2025-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.AddField(
            model_name='user',
            name='professions',
            field=models.ManyToManyField(blank=True, to='users.profession'),
        ),
    ]
