# Generated by Django 5.2.3 on 2025-07-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
        ('users', '0006_user_is_blocked'),
    ]

    operations = [
    ]
