# Generated by Django 5.2.3 on 2025-07-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0005_user_username_0006_user_is_blocked'),
        ('users', '0007_remove_user_profession_user_professions'),
    ]

    operations = [
    ]
