# Generated by Django 4.2 on 2025-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_profession_user_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
