# Generated by Django 4.2 on 2025-07-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250722_1744'),
        ('users', '0008_user_passport_id_user_personal_number'),
    ]

    operations = [
    ]
