# Generated by Django 4.2 on 2025-08-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_legaldocument'),
        ('users', '0009_merge_20250728_1807'),
    ]

    operations = [
    ]
