# Generated by Django 4.2 on 2025-08-03 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpaymentterms',
            options={'verbose_name': 'Условия оплаты картой', 'verbose_name_plural': 'Условия оплаты картой'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политики конфиденциальности'},
        ),
        migrations.AlterModelOptions(
            name='publicoffer',
            options={'verbose_name': 'Публичная оферта', 'verbose_name_plural': 'Публичные оферты'},
        ),
        migrations.AlterModelOptions(
            name='refundpolicy',
            options={'verbose_name': 'Политика возврата', 'verbose_name_plural': 'Политики возврата'},
        ),
        migrations.AlterField(
            model_name='cardpaymentterms',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='HTML-содержимое условий оплаты картой'),
        ),
        migrations.AlterField(
            model_name='cardpaymentterms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='HTML-содержимое политики конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='HTML-содержимое публичной оферты'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='HTML-содержимое политики возврата'),
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
