# Generated by Django 4.2 on 2025-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_cardpaymentterms_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для баннера',
                'verbose_name_plural': 'Фото для баннера',
            },
        ),
    ]
